### ISSUE TITLE
Análisis set "Demografía"

### ISSUE THREAD

**Issue by juz1001** [NuriaVP/El-precio-de-la-discapacidad#12]
El set demografía tiene la extensión ".xsls" y contiene dos columnas para ver la proporción demográfica que presenta cada comunidad autónoma española.

**Comment by NuriaVP** [comment]
Está hecho el análisis estadístico y gráfico en el commit "Análisis Demografía y Contaminación 31-10-21"

**Comment by NuriaVP** [comment]
También he incluido otro set de datos, "Pueblos", para comprobar que comunidad autónoma tiene mayor número de pueblos.
